### ISSUE TITLE
exccause register missing (LLVM-59)

### ISSUE THREAD

**Issue by MabezDev** [espressif/llvm-project#15]
Trying to compile the following function with inline asm to read the exccause reg
```rust
#[no_mangle]
pub unsafe extern "C" fn _rust_user_exc() {
    let mut cause: u32;
    asm!("rsr.exccause a2" : "={a2}"(cause) );
}
```
leads to

```rust
error: <inline asm>:1:2: error: invalid register name
        rsr.exccause a2
        ^

  --> src/lib.rs:45:14
```

I ended up tracking down the register definitions, it seems like exccause is missing or has been [split up for some reason](https://github.com/espressif/llvm-project/blob/96ef209fd7cb4ad374e111fcf02491c4e1de1845/llvm/lib/Target/Xtensa/XtensaRegisterInfo.td#L107)

**Comment by igrr** [comment]
Indeed it is missing, it should be reg. 232: https://github.com/espressif/esp-idf/blob/f5b82c5b1f33f5287f9b5f1993594bf53755a4f2/components/xtensa/include/xtensa/specreg.h#L98
