### ISSUE TITLE
Support for LLVM 10 (LLVM-63)

### ISSUE THREAD

**Issue by aykevl** [espressif/llvm-project#18]
Perhaps a bit premature, but LLVM 10 can be released any moment now: RC 4 has just been tagged:
https://lists.llvm.org/pipermail/llvm-dev/2020-March/139905.html.

Any idea when the rebase on LLVM 10 will happen?

**Comment by andreisfr** [comment]
Hi @aykevl ! There is no significant problems to rebase Xtensa backend on LLVM 10, we already have version rebased on early LLVM 10.  I think soon after  LLVM 10.0.0 release we will verify last changes, test and publish new rebased version.

**Comment by deadprogram** [comment]
LLVM 10 is now out. Will there be a rebased version soon? Thank you!

**Comment by deadprogram** [comment]
Any action here? @andreisfr we really want this! :smile_cat:

**Comment by andreisfr** [comment]
@deadprogram , we are preparing and testing new version, hope it will be available soon)

**Comment by aykevl** [comment]
@andreisfr any update? A recent LLVM version is required for TinyGo and forking this fork just for Xtensa support is difficult.

**Comment by AshUK** [comment]
+1 we are keen to see this as we currently use clang 10 for static analysis on our projects

**Comment by andreisfr** [comment]
Hello @aykevl , @AshUK ! We significally refactored series of  patches implementing the Xtensa backend and ported it on Clang/LLVM release 10. So, this process took a some time. Current version is under review, probably review process will be finished in 1-2 weeks and then we will upload new version.

**Comment by igrr** [comment]
Thanks for the patience everyone. The patches based on release 10 are now available in https://github.com/espressif/llvm-project/pull/30.
