### ISSUE TITLE
Optimized support for llvm.fshr and llvm.fshl intrinsics (LLVM-68)

### ISSUE THREAD

**Issue by arjanmels** [espressif/llvm-project#21]
Optimized support for the llvm.fshr and llvm.fshl intrinsics would be nice: the Xtensa core has special support for 64->32 bit (SRC instruction) and these intrinsics could make use of that, while currently, 7 instructions (including a branch) are emitted.

These intrinsics are useful e.g. in handling unaligned data.

(Further optimization possibility is that the SAR register is only loaded, when value is different from previously for all shift instructions.)

**Comment by igrr** [comment]
Should be implemented in https://github.com/espressif/llvm-project/pull/30/commits/6fbc60664a7a6c63451d7c64b2963cf616635143, thanks for reporting!

**Comment by arjanmels** [comment]
Thanks!
