### ISSUE TITLE
Special Register INT_CLEAR (227) missing (LLVM-70)

### ISSUE THREAD

**Issue by arjanmels** [espressif/llvm-project#23]
Special Register INT_CLEAR (227) missing

**Comment by andreisfr** [comment]
Hi, @arjanmels ! Thanky you for information. What version of Xtensa backend did you use? The xtensa_release_9.0.1 impements "intclear" register.

**Comment by arjanmels** [comment]
@andreisfr Thanks and apologies. I was using https://github.com/MabezDev/rust-xtensa, turns out that the llvm submodule indeed points to an old commit, not the latest.
