### ISSUE TITLE
User registers fsr,, fcr, f64r_lo, f64_hi, f64s not implemented (LLVM-71)

### ISSUE THREAD

**Issue by arjanmels** [espressif/llvm-project#24]
The RUR and WUR instructions are not implemented for user registers: fsr,, fcr, f64r_lo, f64_hi, f64s.

**Comment by andreisfr** [comment]
@arjanmels, please try to use latest branch xtensa_release_9.0.1, it impements fsr..f64s registers.

**Comment by arjanmels** [comment]
@andreisfr Thanks and apologies. I was using https://github.com/MabezDev/rust-xtensa, turns out that the llvm submodule indeed points to an old commit, not the latest.
