### ISSUE TITLE
LLVM 11 support

### ISSUE THREAD

**Issue by aykevl** [espressif/llvm-project#40]
LLVM 11 was released a few weeks ago. Any idea when this Xtensa fork will be updated to LLVM 11?

**Comment by katyo** [comment]
> LLVM 11 was released a few weeks ago. Any idea when this Xtensa fork will be updated to LLVM 11?

Despite of which is not so hard, but where is any reasons to prioritize rebase to latest llvm when more important things still undone.

**Comment by aykevl** [comment]
> > LLVM 11 was released a few weeks ago. Any idea when this Xtensa fork will be updated to LLVM 11?
> 
> Despite of which is not so hard, but where is any reasons to prioritize rebase to latest llvm when more important things still undone.

It is important because otherwise [TinyGo](https://tinygo.org/) might drop support for the ESP32 and ESP8266. We need LLVM 11 for improvements (especially in the AVR backend) so staying on LLVM 10 is not an option.

**Comment by andreisfr** [comment]
Hi @aykevl ! We rebased Xtensa backend on LLVM 11, now we verifying/debugging it, probably it will be ready for upload to github in 1-2 weeks.

**Comment by igrr** [comment]
@aykevl the branch based on release/11.x has been published: https://github.com/espressif/llvm-project/pull/42.

**Comment by aykevl** [comment]
Thanks a lot! Then I consider this issue fixed.
