### ISSUE TITLE
LLVM 12 support (LLVM-95)

### ISSUE THREAD

**Issue by aykevl** [espressif/llvm-project#46]
Can you rebase this fork on LLVM 12? This version of LLVM has been out for some time, so to not fall behind it's important to update it.

**Comment by andreisfr** [comment]
Hi, @aykevl! We rebased this fork on LLVM 12.0.1 and now verifying it. Soon we will upload new release.

**Comment by aykevl** [comment]
Thanks a lot!

**Comment by INetBowser** [comment]
Hi, just wanted to ask when we can expect the LLVM 12 release? Thanks in advance.

**Comment by igrr** [comment]
The default branch has been updated to release 12!

**Comment by igrr** [comment]
The default branch has been updated to release 13.
