### ISSUE TITLE
Xtensa.td feature typo (LLVM-97)

### ISSUE THREAD

**Issue by MabezDev** [espressif/llvm-project#47]
https://github.com/espressif/llvm-project/blob/36dbc8b5ee7dae4a4c5bff73efff0ea7ccb3707e/llvm/lib/Target/Xtensa/Xtensa.td#L100

should say "memctl", not "atomctl"

**Comment by KerryRJ** [comment]
Another one, should say "highpriinterrupts" and not "exception"
```
def FeatureHighPriInterrupts : SubtargetFeature<"exception",
                                                "HasHighPriInterrupts", "true",
                                                "Enable Xtensa HighPriInterrupts option">;
```
