### ISSUE TITLE
Port to LLVM 14 (LLVM-146)

### ISSUE THREAD

**Issue by berolinux** [espressif/llvm-project#54]
Hi,
LLVM 14 is about to be released -- is there a port of the Xtensa patches already? If not, is https://github.com/espressif/llvm-project/pull/51 still considered a complete list of patches that would need to be pulled in/ported?

**Comment by igrr** [comment]
Hi @berolinux,

We are working on the patch set based on LLVM 14 and will release it in a few days if things go well.
The patches are roughly similar to #51, but include a few more fixes we have done recently.

**Comment by igrr** [comment]
@berolinux @aykevl the patches have been rebased to release 14 (https://github.com/espressif/llvm-project/pull/57) and the default branch has been updated.
